language: generic
deploy:
  provider: s3
  access_key_id: AKIAIQDBPHNYY7WPLTAQ
  secret_access_key: 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
    bucket: git-to-amazon-s3-outputbucket-1urzfqv2b7blf
  on:
    repo: Tarix07/Labs
  acl: public_read